version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile.dev     # Use this if you have a dev-specific Dockerfile; otherwise remove.
    environment:
      - DEBUG=${DEBUG}
      - DEBUG_PORT=${DEBUG_PORT}
      - RUN_MAIN=${RUN_MAIN}
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - .:/app
