# Must be explicitly run via -> docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod  # Production Dockerfile
    container_name: versa_forge_api
    environment:
      - APP_ENV=production
      - DEBUG=False
    restart: always
    ports:
      - "8000:8000"
    command: ["fastapi", "run", "app/main.py", "--host", "0.0.0.0", "--port", "8000"]

  # db:
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data  # Persistent storage in production
